// CONTACTS
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

// DISPLAY
export const SET_OPEN_CONTACT = 'SET_OPEN_CONTACT';
export const SET_CONTACT_VIEW_VISIBILITY = 'SET_CONTACT_VIEW_VISIBILITY';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
